default: &default
  title: 'Shoutout-API'

  domains:
    live: 'shoutout.jetzt'
    production: 'shoutout-app-api.herokuapp.com'
    staging: ''
    preview: 'shoutout-app-api-preview.herokuapp.com'
    development: ''

  hosting:
    - production
    - staging
    - preview
    - localhost:3020 # TODO: local-domain ~ pow

  email:

  debug:
    app: true

  user:
    role_wordings:
      guest: 'Gast'
      user: 'Benutzer'
      administrator: 'Administrator'
      developer: 'Entwickler'


development:
  <<: *default
staging:
  <<: *default
production:
  <<: *default
preview:
  <<: *default
test:
  <<: *default
